config/routes.rb
Rails.application.routes.draw do 
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'notifications/index'

  

  devise_for :users
  root 'tracks#index'

  resources :users
  
  resources :tracks do
    member do
      put "like", to: "tracks#upvote"
      put "dislike", to: "tracks#downvote"
    end  
  end

  authenticated :user do
    root  "tracks#profile_track", as: :root_user, via: :get
  end

  post 'tracks/:id/' => 'tracks#destroy', method: :delete, as: 'delete_track'
  
  get 'tracks/:id/profile_track' => 'tracks#profile_track' , as: 'profile_track'

  resources :comments 
  post 'comments/:id/' => 'comments#delete', method: :delete, as: 'delete_comment'

  resources :notifications
  post 'notifications/:id/' => 'notifications#delete', method: :delete, as: 'delete_notification'

  resources :mailboxer

  resources :tags

  get "/messages" => redirect("/conversations")

  resources :messages do
    member do
      post :new
    end
  end

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
    collection do
      get :trashbin
      post :empty_trash
    end
  end

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :track
  belongs_to :user
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @conversations = current_user.mailbox.conversations
    @notifications = current_user.mailbox.notifications.group_by &:sender_id
    @receipts = current_user.mailbox.receipts
    @message = current_user.mailbox.inbox.first.messages.first.body

  end

  def new
    @user = User.find(params[:user])
    @message = current_user.messages.new
  end
 
  def create
    @recipient = User.find_by(params[:id])
    current_user.send_message(@recipient, params[:body], params[:subject])
    flash[:notice] = "Message has been sent"
    redirect_to :conversations
  end


end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.haml
.container
  %h3 Reply:
  %br
  = form_tag reply_conversation_path(conversation), method: :post do
    .form-group
      = text_area_tag 'body', nil, cols: 2, class: 'form-control', placeholder: 'Type your message here!', required: true
      = submit_tag "Send Message", class: 'btn btn-primary'

app/views/messages/index.html.haml
.well
  - @conversations.each do |conversation|
    %ol.posts
      %li
        %p= conversation.subject
        %p= conversation.created_at
= link_to 'mes convertations', :conversations

app/views/messages/new.html.haml
.well
  %p
    %h3
      Send a message to #{@user.firstname}  #{@user.lastname}
    %p
      = form_tag({controller: "messages", action: "create"}, method: :post) do
        %p
          = label_tag :subject
          %br
          = text_field_tag :subject
        %p
          = label :body, "Message text"
          %br
          = text_area_tag :body
        %p
          = hidden_field :user_id, value: @user.id
          
          = submit_tag 'Send message', class: "btn btn-primary"
          
            