config/routes.rb
Rails.application.routes.draw do 
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'notifications/index'

  

  devise_for :users
  root 'tracks#index'

  resources :users
  
  resources :tracks do
    member do
      put "like", to: "tracks#upvote"
      put "dislike", to: "tracks#downvote"
    end  
  end

  authenticated :user do
    root  "tracks#profile_track", as: :root_user, via: :get
  end

  post 'tracks/:id/' => 'tracks#destroy', method: :delete, as: 'delete_track'
  
  get 'tracks/:id/profile_track' => 'tracks#profile_track' , as: 'profile_track'

  resources :comments 
  post 'comments/:id/' => 'comments#delete', method: :delete, as: 'delete_comment'

  resources :notifications
  post 'notifications/:id/' => 'notifications#delete', method: :delete, as: 'delete_notification'

  resources :mailboxer

  resources :tags

  get "/messages" => redirect("/conversations")

  resources :messages do
    member do
      post :new
    end
  end

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
    collection do
      get :trashbin
      post :empty_trash
    end
  end

end

app/models/track.rb
class Track < ActiveRecord::Base
  
  has_many :comments
  belongs_to :user
  has_many :votes
  has_many :tags, through: :taggings, :dependent => :destroy
  has_many :taggings
  has_many :notifications

  #before_save :create_tag

  acts_as_votable 
  acts_as_messageable
  
  has_attached_file :avatar, 
                      :storage => :filesystem,
                      default_url: "/images/:style/missing.png",
                      :path => ":rails_root/public/system/:class/:attachment/:id/:style/:basename.:extension",
                      :url => '/system/:class/:attachment/:id/:style/:basename.:extension'
  unless Rails.env.production?
    has_attached_file :avatar,
                      :storage => :s3,
                      :bucket => ENV['S3_BUCKET_NAME'],
                      :s3_region => ENV['AWS_REGION'],
                      :s3_credentials => "#{Rails.root}/config/s3.yml",
                      :url => ":s3_domain_url",
                      :path => '/:class/:attachment/:id_partition/:style/:filename'
  end
 
  validates_attachment_content_type :avatar, :content_type => [ 'image/png','image/jpeg']

  has_attached_file :audio
  validates_attachment_presence :audio
  validates_attachment_content_type :audio, :content_type => [ 'audio/mp3','audio/mpeg']


  def score
    self.get_upvotes.size - self.get_downvotes.size
  end

  def self.search(search)
    search = self.joins(:tags)
    search.where('tags.name ILIKE ?', "%#{search}%")
    where('audio_file_name ILIKE ?',"%#{search}%")
  end



  #def create_tag
  #  @tags_array = []
  #  @tags = Tag.all
 #   @tag = self.tags.new params[:tag]
  #  @tags_array.map do |tag|
  #    if tag == 1
  #      Tag.find(tag)
  #    else
  #      @tags_array << Tag.create(name: tag)
  #    end
  #  end
  #end


end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :authenticate_user!, except: :index
  SEND_FILE_METHOD = :default

  def index
    @tracks = Track.includes(:comments, :tags)
    @comment = Comment.new
    if(params[:search])
      @tracks = Track.search(params[:search]).order('created_at DESC')
    else
      @tracks = Track.all.order('created_at DESC')
    end
  end

  def new
    @track = Track.new
    @tag = Tag.new
  end

  def profile_track
    @tracks = Track.where(user_id: current_user).all
    @comment = Comment.new
  end

  def create
    @track = current_user.tracks.new(track_params)
    if @track.save
      redirect_to tracks_path, notice: "thanks #{@track.user.email} for your upload!"
    else
      render 'new'
    end
  end

  def search
  end


  def destroy
    @track = Track.find(params[:id])
    @track.destroy
    redirect_to tracks_path
  end

  def show
    @track = Track.find(params[:id])
    @comments = @track.comments.all
  end

  def upvote
    @track = Track.find(params[:id])
    @track.upvote_by current_user
    redirect_to tracks_path
  end


  private

  def track_params
    params.require(:track).permit(:avatar, :audio, :user_id)
  end
end

app/helpers/tracks_helper.rb
module TracksHelper
  
  def find_name(user_id)
    User.find(user_id).name
  end

 

end

app/views/tracks/_form.html.haml
.form
  - form_tag() do
    %p
      = f.label_tag :tags
    %p
      = text_field_tag :tags, params[:tags]

app/views/tracks/_search.html.haml
= form_tag(tracks_path, :method => "get", id: "search-form") do
  = text_field_tag :search, params[:search], placeholder: "Search tracks"
  = submit_tag "Search"
  - if @track.present?
    = link_to_function "Clear", "$('search_field').clear()"
  - else
    %p
      = "There are no Track match with '#{params[:search]}'"

app/views/tracks/_search_results.html.haml
%ul
  - @tracks.each do |track|
    %li= link_to grant.title, :action => 'show', :id => track.id 

app/views/tracks/index.html.haml
//= render :partial => "tracks/search" 
- if user_signed_in?
-else
  = render 'layouts/header'
.row.col-md-12
  - @tracks.each do |track|
    .sound-content.gutter.col-md-2.col-sm-4.col-lg-3
      .name_user
        = track.user.firstname
        = track.user.lastname
      = link_to track_path(track.id) do
        .covermusic
          = image_tag track.avatar.url, class: 'img-responsive'
      %p
      / /* audio player */
      .audio-player
        .bbplayer
          %span.bb-rewind
          %span.bb-play
          %span.bb-forward
          %span.bb-trackTime
          %span.bb-trackLength
          %span.bb-trackTitle
          %audio
            %source{:src => "#{track.audio.url}"}
            %source{:src => "#{track.audio.url}"}
      / /* commentaire */
      .comment_track
      / /* bouton pour supprimer */
      .sound-footer
      - if user_signed_in?
        %p.like-delete
          .btn.btn-circle-micro.btn-primary.glyphicon
            %span= link_to "", like_track_path(track), method: :put, class: 'glyphicon-thumbs-up'
          = track.score
          %a.btn.btn-circle-micro.btn-primary{"data-target" => "#myModal", "data-toggle" => "modal", :href => "#aboutModal"}
            %span.glyphicon.glyphicon-comment
          = track.comments.size
          #myModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
            .modal-dialog
              .modal-content
                .modal-header
                  %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} X
                  %h4#myModalLabel.modal-title Commentaire:
                .modal-body
                  %center
                    %br/
                    %h3.media-heading 
                      - if user_signed_in?
                        = render 'comments/new', locals: {track: track}
                      - else
                .modal-footer
                  %center
                    %button.btn.btn-circle.btn-default{"data-dismiss" => "modal", :type => "button"}
                      %span.glyphicon.glyphicon-remove
          -if current_user.id == track.user_id
            .btn.btn-circle-micro.btn-primary.glyphicon
              %span= link_to "".html_safe, delete_track_path(track.id),method: :delete, class: 'glyphicon-trash'
          - else
      - else
%script{:src => "https://raw.githubusercontent.com/73rhodes/bbplayer/master/js/bbplayer.js"}

app/views/tracks/new.html.haml
%h2 Upload On Decibel!
%p
.row
  = form_for @track do |t|
    .avatar_preview.col-md-6
      .ava_prev{id: 'image-frame', width: "300", height: "300"}
    .upload_file.col-md-6
      .avatar_file
        %p
          = t.label "cover"
        %p
          = t.file_field :avatar, id: 'avatar_file'
      .audio_file
        %p
        /  = render 'tags/form'
        %p
          = t.label "choose your music"
        %p
          = t.file_field :audio
        %p.upload
          %h4 Let's Go!!
        = t.submit "upload"
:javascript
  $("#avatar_file").change(function () {
        displayThumbnail(this);
  });
  function displayThumbnail(input) {
        for( var i = 0;i<input.files.length;i++){
            if (input.files && input.files[i]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    if ($('#avatar_file')) {
                        var $newImageThumbnail = makeElement('img',{ class: "image-frame",src: e.target.result});
                        $('#image-frame').append($newImageThumbnail);
                    }
                };
                reader.readAsDataURL(input.files[i]);
            }
        }

    }

    function makeElement(element, options) {
        var $elem = document.createElement(element);
        $.each(options, function (key, value) {
            $elem.setAttribute(key, value);
        });
        return $elem;
    }

app/views/tracks/profile_track.html.haml
.row.header_profile.col-md-12
  .profile_track_avatar.col-md-3
    = image_tag current_user.avatar.url , class: 'img-responsive', id: 'profile_avatar'
  .user_name.col-md-9
    %b.user_identity
      = current_user.firstname
      %br
      = current_user.lastname
%ul.nav.nav-tabs
  %li.active
    %a{"data-toggle" => "tab", :href => "#home"} TRACKS
  %li
    %a{"data-toggle" => "tab", :href => "#menu1"} Menu 1
  %li
    %a{"data-toggle" => "tab", :href => "#menu2"} Menu 2
  %li
    %a{"data-toggle" => "tab", :href => "#menu3"} Menu 3
.tab-content
  #home.tab-pane.fade.in.active
    %h3 All my tracks
    %p 
      - @tracks.each do |track|
        .sound-content.gutter.col-md-2.col-sm-4.col-lg-3
          = link_to track_path(track.id) do
            .covermusic
              = image_tag track.avatar.url, class: 'img-responsive'
          / /* audio player */
          .audio-player
            .bbplayer
              %span.bb-rewind
              %span.bb-play
              %span.bb-forward
              %span.bb-trackTime
              %span.bb-trackLength
              %span.bb-trackTitle
              %audio
                %source{:src => "#{track.audio.url}"}
                %source{:src => "#{track.audio.url}"}
          / /* bouton pour supprimer */
          .sound-footer
            %p.like-delete
              = track.score
              = link_to "<i class='fa fa-heartbeat fa-lg'></i>".html_safe, like_track_path(track), method: :put
              = link_to "<i class='fa fa-trash-o fa-lg'></i>".html_safe, delete_track_path(track.id),method: :delete
          %script{:src => "https://raw.githubusercontent.com/73rhodes/bbplayer/master/js/bbplayer.js"}
  #menu1.tab-pane.fade
    %h3 Menu 1
    %p En cours
  #menu2.tab-pane.fade
    %h3 Menu 2
    %p En cours
  #menu3.tab-pane.fade
    %h3 Menu 3
    %p En cours

app/views/tracks/show.html.haml
.row.contenttrack-show
  .covermusic-show.col-md-4.col-lg-4
    = image_tag @track.avatar.url, class: 'img-show'
  .sound-content-show.col-md-6.col-lg-6
    .name_user
      %b
        = @track.user.firstname
        = @track.user.lastname
    .audio-player-show
      .bbplayer
        %span.bb-rewind
        %span.bb-play
        %span.bb-forward
        %span.bb-trackTime
        %span.bb-trackLength
        %span.bb-trackTitle
        %audio
          %source{:src => "#{@track.audio.url}"}
          %source{:src => "#{@track.audio.url}"}
          %source{:src => "#{@track.audio.url}"}
          %source{:src => "#{@track.audio.url}"}
    .sound-footer-show
      %p.like-delete-show
        .track_button
          = link_to like_track_path(@track), method: :put do
            %i.fa.fa-heartbeat.fa-lg
            J'aime
            = @track.score
        .track_button
          = link_to delete_track_path(@track.id), method: :delete do
            %i.fa.fa-trash-o.fa-lg
            Ordure
        .track_button
          = link_to new_message_path(:user => @track.user_id), method: :post do
            %i.fa.fa-envelope-o
            Message
      .comment_all
        %i.fa.fa-comment-o
          Commentaires:
        %hr
        = render "comments/index"
%script{:src => "https://raw.githubusercontent.com/73rhodes/bbplayer/master/js/bbplayer.js"}