config/routes.rb
Rails.application.routes.draw do 
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'notifications/index'

  

  devise_for :users
  root 'tracks#index'

  resources :users
  
  resources :tracks do
    member do
      put "like", to: "tracks#upvote"
      put "dislike", to: "tracks#downvote"
    end  
  end

  authenticated :user do
    root  "tracks#profile_track", as: :root_user, via: :get
  end

  post 'tracks/:id/' => 'tracks#destroy', method: :delete, as: 'delete_track'
  
  get 'tracks/:id/profile_track' => 'tracks#profile_track' , as: 'profile_track'

  resources :comments 
  post 'comments/:id/' => 'comments#delete', method: :delete, as: 'delete_comment'

  resources :notifications
  post 'notifications/:id/' => 'notifications#delete', method: :delete, as: 'delete_notification'

  resources :mailboxer

  resources :tags

  get "/messages" => redirect("/conversations")

  resources :messages do
    member do
      post :new
    end
  end

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
    collection do
      get :trashbin
      post :empty_trash
    end
  end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :tracks, through: :taggings, :dependent => :destroy
  has_many :taggings

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = Tag.all
  end

  def new
    @tags = Tag.all
    @tag = Tag.new
  end

  def show
    @tag = Tag.find(params[:id])
  end


  private

  def params_tag
    params.require(:tag).permit(:name)
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.haml
.form
  = form_for @tag do |t|
    %p
      = t.label :tag
    %p
      = t.text_field_tag :name

app/views/tags/_search.html.haml
= form_tag(tags_path, :method => "get", id: "search-form") do
  = text_field_tag :search, params[:search], placeholder: "Search tags"
  = submit_tag "Search"
  - if @track.present?
    = link_to_function "Clear", "$('search_field').clear()"
  - else
    = "There are no Track match with '#{params[:search]}'."

app/views/tags/_search_results.html.haml
%ul
  - @tags.each do |tag|
    %li= link_to grant.title, :action => 'show', :id => tag.id 

app/views/tags/index.html.haml
- @tags.each do |tag|
  = tag.name

app/views/tags/new.html.haml
= form_for @tag do |t|
  = t.select_tag "tag", options_from_collection_for_select(@tag, "id", "name")
  = t.submit 'tagger' 