config/routes.rb
Rails.application.routes.draw do 
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'notifications/index'

  

  devise_for :users
  root 'tracks#index'

  resources :users
  
  resources :tracks do
    member do
      put "like", to: "tracks#upvote"
      put "dislike", to: "tracks#downvote"
    end  
  end

  authenticated :user do
    root  "tracks#profile_track", as: :root_user, via: :get
  end

  post 'tracks/:id/' => 'tracks#destroy', method: :delete, as: 'delete_track'
  
  get 'tracks/:id/profile_track' => 'tracks#profile_track' , as: 'profile_track'

  resources :comments 
  post 'comments/:id/' => 'comments#delete', method: :delete, as: 'delete_comment'

  resources :notifications
  post 'notifications/:id/' => 'notifications#delete', method: :delete, as: 'delete_notification'

  resources :mailboxer

  resources :tags

  get "/messages" => redirect("/conversations")

  resources :messages do
    member do
      post :new
    end
  end

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
    collection do
      get :trashbin
      post :empty_trash
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user 
  belongs_to :track
  has_many :notifications

  before_save :send_notification

  def send_notification
    if user == track_owner
      
    else
      create_notif 
    end
  end

  def create_notif
    Notification.create(user_id: track_owner.id,
                      comment_id: self.user.id,
                      track_id: track.id,
                      content: "Vous avez recu un commentaire!"
                    )
  end
  
  def track_owner
    user = track.user
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :track
  belongs_to :user
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  belongs_to :comment
  belongs_to :message
  belongs_to :track

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :tracks, through: :taggings, :dependent => :destroy
  has_many :taggings

end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :track
  belongs_to :tag
end

app/models/track.rb
class Track < ActiveRecord::Base
  
  has_many :comments
  belongs_to :user
  has_many :votes
  has_many :tags, through: :taggings, :dependent => :destroy
  has_many :taggings
  has_many :notifications

  #before_save :create_tag

  acts_as_votable 
  acts_as_messageable
  
  has_attached_file :avatar, 
                      :storage => :filesystem,
                      default_url: "/images/:style/missing.png",
                      :path => ":rails_root/public/system/:class/:attachment/:id/:style/:basename.:extension",
                      :url => '/system/:class/:attachment/:id/:style/:basename.:extension'
  unless Rails.env.production?
    has_attached_file :avatar,
                      :storage => :s3,
                      :bucket => ENV['S3_BUCKET_NAME'],
                      :s3_region => ENV['AWS_REGION'],
                      :s3_credentials => "#{Rails.root}/config/s3.yml",
                      :url => ":s3_domain_url",
                      :path => '/:class/:attachment/:id_partition/:style/:filename'
  end
 
  validates_attachment_content_type :avatar, :content_type => [ 'image/png','image/jpeg']

  has_attached_file :audio
  validates_attachment_presence :audio
  validates_attachment_content_type :audio, :content_type => [ 'audio/mp3','audio/mpeg']


  def score
    self.get_upvotes.size - self.get_downvotes.size
  end

  def self.search(search)
    search = self.joins(:tags)
    search.where('tags.name ILIKE ?', "%#{search}%")
    where('audio_file_name ILIKE ?',"%#{search}%")
  end



  #def create_tag
  #  @tags_array = []
  #  @tags = Tag.all
 #   @tag = self.tags.new params[:tag]
  #  @tags_array.map do |tag|
  #    if tag == 1
  #      Tag.find(tag)
  #    else
  #      @tags_array << Tag.create(name: tag)
  #    end
  #  end
  #end


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments
  has_many :tracks
  has_many :votes
  has_many :notifications, :foreign_key => "user_id"



  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, 
                    default_url: "/images/:style/missing.png",
                    :storage => :s3,
                    :s3_credentials => {
                      :bucket => ENV['S3_BUCKET_NAME'],
                      :s3_region => ENV['AWS_REGION'],
                      :access_key_id => ENV['AWS_ACCESS_KEY_ID'],
                      :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY'],
                      :url => ":s3_domain_url",
                      :path => '/:class/:attachment/:id_partition/:style/:filename'
                    }


  validates_attachment_content_type :avatar, :content_type => /.*/

  acts_as_messageable



    #Returning any kind of identification you want for the model
  def name
    
  end

  #Returning the email address of the model if an email should be sent for this object (Message or Notification).
  #If no mail has to be sent, return nil.
  def mailboxer_email(object)
    #Check if an email should be sent for that object
    #if true
    return "define_email@on_your.model"
    #if false
    #return nil
  end

 
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = Tag.all
  end

  def new
    @tags = Tag.all
    @tag = Tag.new
  end

  def show
    @tag = Tag.find(params[:id])
  end


  private

  def params_tag
    params.require(:tag).permit(:name)
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :authenticate_user!, except: :index
  SEND_FILE_METHOD = :default

  def index
    @tracks = Track.includes(:comments, :tags)
    @comment = Comment.new
    if(params[:search])
      @tracks = Track.search(params[:search]).order('created_at DESC')
    else
      @tracks = Track.all.order('created_at DESC')
    end
  end

  def new
    @track = Track.new
    @tag = Tag.new
  end

  def profile_track
    @tracks = Track.where(user_id: current_user).all
    @comment = Comment.new
  end

  def create
    @track = current_user.tracks.new(track_params)
    if @track.save
      redirect_to tracks_path, notice: "thanks #{@track.user.email} for your upload!"
    else
      render 'new'
    end
  end

  def search
  end


  def destroy
    @track = Track.find(params[:id])
    @track.destroy
    redirect_to tracks_path
  end

  def show
    @track = Track.find(params[:id])
    @comments = @track.comments.all
  end

  def upvote
    @track = Track.find(params[:id])
    @track.upvote_by current_user
    redirect_to tracks_path
  end


  private

  def track_params
    params.require(:track).permit(:avatar, :audio, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
		@user = User.find(params[:id])
	end

	def new
			
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def notif_count(user)
    user = current_user
    notifications = Notification.where(user_id: user).count
 end

  def find_email(user_id)
    User.find(user_id).email
  end

  def track_owner(user)
    current_user = Track.where(user_id: current_user)
  end

  def bootstrap_flash
    if :notice
      "alert-warning"
    else

    end
  end
  


end

app/helpers/comments_helper.rb
module CommentsHelper
  def find_email(user_id)
    User.find(user_id).email
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
  
  def find_name(user_id)
    User.find(user_id).name
  end

 

end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/_flash_alert.html.haml
- if flash[:notice]
  .alert.alert-warning.collapse.alert-dismissible.fade.in{:role => "alert", id: "flash"}
    %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
      %span{"aria-hidden" => "true"} ×
    %strong HEY!
    = notice
- else
:javascript
  window.setTimeout(function() {
    $(".alert").fadeTo(500, 0).slideUp(500, function(){
      $(this).remove(); 
    });
  }, 3000);

app/views/layouts/_flash_alert_devise.html.haml
.alert.alert-warning.collapse.alert-dismissible.fade.in{:role => "alert", id: "flash"}
  %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
    %span{"aria-hidden" => "true"} ×
  %strong HEY!
  = devise_error_messages!

app/views/layouts/_header.html.haml
.header

app/views/layouts/_navbar.html.haml
.navbar.navbar-inverse.navbar-static-top
  %button.navbar-toggle{"data-target" => ".navbar-responsive-collapse", "data-toggle" => "collapse", :type => "button"}
    %span.icon-bar
    %span.icon-bar
    %span.icon-bar
  %a.navbar-brand{:href => "#"} Decibel
  .navbar-collapse.collapse.navbar-responsive-collapse
    %ul.nav.navbar-nav
      - if user_signed_in?
        %li= link_to "Explore", tracks_path
      - else
        %li= link_to "Home", tracks_path
      - if user_signed_in?
        %li= link_to "Déconnexion", destroy_user_session_path, method: :delete
        %li= link_to "Upload", new_track_path
        %li= link_to "Messages", conversations_path
        %li= link_to "My Tracks", profile_track_path(current_user.id)
        %li.dropdown
          %a#dLabel{"data-target" => "#", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            Notif!
            - if notif_count(current_user) > 0 
              %i.glyphicon.glyphicon-bell
            -else
          %ul.dropdown-menu.notifications{"aria-labelledby" => "dLabel", :role => "menu"}
            .notification-heading
              %h4.menu-title Notifications
              %h4.menu-title.pull-right
                View all
                %i.glyphicon.glyphicon-circle-arrow-right
            %li.divider
            .notifications-wrapper
              - @notifications.each do |notif|
                %a.content{:href => track_path(notif.track.user.id)}
                  .notification-item
                    %h4.item-title 
                      = find_email(current_user)
                    %p.item-info 
                      = notif.content
                      = link_to "supprimer", delete_notification_path(notif.id), method: :delete
            %li.divider
            .notification-footer
              %h4.menu-title
                View all
                %i.glyphicon.glyphicon-circle-arrow-right
        %li.dropdown
          %a.dropdown-toggle{"data-target" => "#", "data-toggle" => "dropdown", :href => "page.html"}
            = current_user.email
            %b.caret
          %ul.dropdown-menu
            %li
              %a= link_to "edit profile", edit_user_registration_path(current_user.id)
            %li
              %a{:href => "#"} Another action
      - else
        %li= link_to "Connexion", new_user_session_path

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
	%head
		%meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
		%meta{:charset => "utf-8"}/
		%meta{:content => "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
		%meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
		%title= content_for?(:title) ? yield(:title) : "Decibel"
		= csrf_meta_tags
		= stylesheet_link_tag "application", :media => "all", 'data-turbolinks-track' => true
		= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
		= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
		= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
		= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
		= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
		= javascript_include_tag "application", 'data-turbolinks-track' => true
		<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
		%script#dropboxjs{"data-app-key" => "kn86a7sgogxq79a", :src => "https://www.dropbox.com/static/api/2/dropins.js", :type => "text/javascript"}
	%body
		= render 'layouts/navbar'
		.container
			= render 'layouts/flash_alert'
			= yield